# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the Dataset

In [2]:
df = pd.read_csv("online_retail_II.csv")

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
# Basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [4]:
# Statistical summary of numerical columns
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [5]:
# Number of missing values in each column
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [6]:
df.shape

(1067371, 8)

In [11]:
df.duplicated().sum()

np.int64(34335)

In [47]:
# Check how many invoices are cancellations

cancelled = df['Invoice'].astype(str).str.startswith('C')

cancelled.sum()

np.int64(19494)

In [48]:
# Percentage of transactions that are cancellations

(cancelled.mean() * 100)

np.float64(1.8263565339511754)

In [49]:
df[cancelled].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [50]:
# Find negative quantities that are NOT cancellation invoices

negative_qty = df['Quantity'] < 0

negative_not_cancelled = df[negative_qty & ~cancelled]

negative_not_cancelled.shape

(3457, 8)

In [51]:
# Look at some examples

negative_not_cancelled.head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6911,490007,84347,21494,-720,2009-12-03 12:09:00,0.0,NaN,United Kingdom
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom
9308,490130,21493,lost?,-600,2009-12-03 18:28:00,0.0,NaN,United Kingdom
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom
11973,490354,21489,NaN,-23,2009-12-04 16:39:00,0.0,NaN,United Kingdom

In [52]:
# Compare transactions with and without Customer ID

df['Customer ID'].isnull().value_counts()

Customer ID
False    824364
True     243007
Name: count, dtype: int64

In [53]:
# Look at transactions where Customer ID is missing

df[df['Customer ID'].isnull()].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1058,489548,22195,LARGE HEART MEASURING SPOONS,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom
1059,489548,22131,FOOD CONTAINER SET 3 LOVE HEART,2,2009-12-01 12:32:00,1.95,NaN,United Kingdom
1060,489548,22079,RIBBON REEL HEARTS DESIGN,10,2009-12-01 12:32:00,1.65,NaN,United Kingdom
1061,489548,22138,BAKING SET 9 PIECE RETROSPOT,3,2009-12-01 12:32:00,4.95,NaN,United Kingdom
1062,489548,22147,FELTCRAFT BUTTERFLY HEARTS,2,2009-12-01 12:32:00,1.45,NaN,United Kingdom
1063,489548,22142,CHRISTMAS CRAFT WHITE FAIRY,2,2009-12-01 12:32:00,1.45,NaN,United Kingdom
1064,489548,22150,3 STRIPEY MICE FELTCRAFT,2,2009-12-01 12:32:00,1.95,NaN,United Kingdom
1065,489548,20804,GLASS CHICKEN BUTTER DISH,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom
1066,489548,22196,SMALL HEART MEASURING SPOONS,8,2009-12-01 12:32:00,0.85,NaN,United Kingdom
1067,489548,22086,PAPER CHAIN KIT 50'S CHRISTMAS,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1068,489548,21115,ROSE CARAVAN DOORSTOP,1,2009-12-01 12:32:00,6.75,NaN,United Kingdom

In [54]:
# What percentage of the dataset has a missing Customer ID?

df['Customer ID'].isnull().mean() * 100

np.float64(22.766872999172733)

In [55]:
# Missing Customer ID: positive quantity vs negative quantity

missing_customer = df['Customer ID'].isnull()

df.loc[missing_customer, 'Quantity'].gt(0).value_counts()

Quantity
True     238801
False      4206
Name: count, dtype: int64

In [56]:
# Missing Customer ID: how many have zero price?

df.loc[missing_customer, 'Price'].eq(0).value_counts()

Price
False    236876
True       6131
Name: count, dtype: int64

In [57]:
# Summary of transactions with missing Customer ID

df.loc[missing_customer, ['Quantity', 'Price']].describe()

            Quantity          Price
count  243007.000000  243007.000000
mean        1.540548       7.948744
std        98.859370     224.275451
min     -9600.000000  -53594.360000
25%         1.000000       1.660000
50%         1.000000       3.290000
75%         2.000000       5.790000
max     10200.000000   25111.090000

In [58]:
# Check how many transactions have a negative price

negative_price = df['Price'] < 0

negative_price.sum()

np.int64(5)

In [59]:
# Look at the transactions with negative prices

df[negative_price].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [60]:
# Check whether these negative-price transactions have Customer IDs

df.loc[negative_price, 'Customer ID'].notnull().value_counts()

Customer ID
False    5
Name: count, dtype: int64

In [61]:
# Convert InvoiceDate to datetime

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['InvoiceDate'].min(), df['InvoiceDate'].max()

(Timestamp('2009-12-01 07:45:00'), Timestamp('2011-12-09 12:50:00'))

In [62]:
# Check whether any dates failed to convert

df['InvoiceDate'].isnull().sum()

np.int64(0)

In [63]:
# Number of rows after removing exact duplicates

df_clean = df.drop_duplicates()

df_clean.shape

(1033036, 8)

In [64]:
# How many rows were removed?

df.shape[0] - df_clean.shape[0]

34335

In [65]:
# Remove cancellation transactions

df_clean = df_clean[
    ~df_clean['Invoice'].astype(str).str.startswith('C')
]

df_clean.shape

(1013932, 8)

In [66]:
df_clean['Invoice'].astype(str).str.startswith('C')

0          False
1          False
2          False
3          False
4          False
           ...
1067366    False
1067367    False
1067368    False
1067369    False
1067370    False
Name: Invoice, Length: 1013932, dtype: bool

In [67]:
# Check that no cancellation invoices remain

df_clean['Invoice'].astype(str).str.startswith('C').sum()

np.int64(0)

In [68]:
# Check remaining negative quantities

(df_clean['Quantity'] < 0).sum()

np.int64(3393)

In [69]:
# Look at the remaining negative-quantity records

df_clean[df_clean['Quantity'] < 0].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6911,490007,84347,21494,-720,2009-12-03 12:09:00,0.0,NaN,United Kingdom
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom
9308,490130,21493,lost?,-600,2009-12-03 18:28:00,0.0,NaN,United Kingdom
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom
11973,490354,21489,NaN,-23,2009-12-04 16:39:00,0.0,NaN,United Kingdom

In [70]:
# Keep only transactions with positive quantities

df_clean = df_clean[df_clean['Quantity'] > 0]

df_clean.shape

(1010539, 8)

In [71]:
# Confirm that no negative quantities remain

(df_clean['Quantity'] < 0).sum()

np.int64(0)

In [72]:
# Check remaining missing Customer IDs

df_clean['Customer ID'].isnull().sum()

np.int64(231044)

In [73]:
# Percentage of remaining transactions without Customer ID

df_clean['Customer ID'].isnull().mean() * 100

np.float64(22.8634421828351)

In [74]:
# Keep only transactions with a known Customer ID

df_clean = df_clean.dropna(subset=['Customer ID'])

df_clean.shape

(779495, 8)

In [75]:
# Confirm that no Customer IDs are missing

df_clean['Customer ID'].isnull().sum()

np.int64(0)

In [77]:
# Make df_clean an independent DataFrame

df_clean = df_clean.copy()

In [78]:
# Calculate revenue for each transaction

df_clean['Revenue'] = df_clean['Quantity'] * df_clean['Price']

In [79]:
df_clean[['Quantity', 'Price', 'Revenue']].head(10)

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0
5        24   1.65     39.6
6        24   1.25     30.0
7        10   5.95     59.5
8        12   2.55     30.6
9        12   3.75     45.0

In [80]:
df_clean['Revenue'].describe()

count    779495.000000
mean         22.289821
std         227.416962
min           0.000000
25%           4.950000
50%          12.480000
75%          19.800000
max      168469.600000
Name: Revenue, dtype: float64

In [81]:
# Number of unique customers

df_clean['Customer ID'].nunique()

5881

In [82]:
# Number of unique invoices/orders

df_clean['Invoice'].nunique()

36975

In [83]:
# Total revenue generated by the cleaned transactions

df_clean['Revenue'].sum()

np.float64(17374804.268)

# Exploratory Data Analysis

In [84]:
# Number of invoices/orders made by each customer

orders_per_customer = df_clean.groupby('Customer ID')['Invoice'].nunique()

orders_per_customer.describe()

count    5881.000000
mean        6.287196
std        13.012879
min         1.000000
25%         1.000000
50%         3.000000
75%         7.000000
max       398.000000
Name: Invoice, dtype: float64

In [85]:
# How many customers made only one purchase?

(orders_per_customer == 1).sum()

np.int64(1626)

In [86]:
# How many customers made more than one purchase?

(orders_per_customer > 1).sum()

np.int64(4255)

In [87]:
# Total revenue generated by each customer

revenue_per_customer = df_clean.groupby('Customer ID')['Revenue'].sum()

revenue_per_customer.describe()

count      5881.000000
mean       2954.396237
std       14437.322635
min           0.000000
25%         341.900000
50%         865.600000
75%        2247.720000
max      580987.040000
Name: Revenue, dtype: float64

In [88]:
# Customers with the highest total revenue

revenue_per_customer.sort_values(ascending=False).head(10)

Customer ID
18102.0    580987.04
14646.0    528602.52
14156.0    313437.62
14911.0    291420.81
17450.0    244784.25
13694.0    195640.69
17511.0    172132.87
16446.0    168472.50
16684.0    147142.77
12415.0    144458.37
Name: Revenue, dtype: float64

In [89]:
# Find customers with zero total revenue

revenue_per_customer[revenue_per_customer == 0]

Customer ID
13256.0    0.0
14103.0    0.0
14827.0    0.0
Name: Revenue, dtype: float64

In [90]:
# How many customers have zero revenue?

(revenue_per_customer == 0).sum()

np.int64(3)

In [91]:
# Inspect their transactions

df_clean[
    df_clean['Customer ID'].isin(
        revenue_per_customer[revenue_per_customer == 0].index
    )
][['Customer ID', 'Invoice', 'Quantity', 'Price', 'Revenue']].head(20)

         Customer ID Invoice  Quantity  Price  Revenue
89084        14103.0  497819         5    0.0      0.0
89180        14827.0  497843         5    0.0      0.0
1027583      13256.0  578841     12540    0.0      0.0

In [92]:
# Keep only transactions with a positive price

df_clean = df_clean[df_clean['Price'] > 0].copy()

df_clean.shape

(779425, 9)

In [93]:
# Verify that no zero or negative prices remain

(df_clean['Price'] <= 0).sum()

np.int64(0)

# Recency

In [94]:
# Latest transaction date in our RFM dataset

df_clean['InvoiceDate'].max()

Timestamp('2011-12-09 12:50:00')

In [95]:
# Reference date for calculating recency

reference_date = df_clean['InvoiceDate'].max() + pd.Timedelta(days=1)

reference_date

Timestamp('2011-12-10 12:50:00')

In [96]:
# Find each customer's most recent purchase date

last_purchase = df_clean.groupby('Customer ID')['InvoiceDate'].max()

last_purchase.head()

Customer ID
12346.0   2011-01-18 10:01:00
12347.0   2011-12-07 15:52:00
12348.0   2011-09-25 13:13:00
12349.0   2011-11-21 09:51:00
12350.0   2011-02-02 16:01:00
Name: InvoiceDate, dtype: datetime64[ns]

In [97]:
# Calculate Recency for each customer

recency = (reference_date - last_purchase).dt.days

recency.head()

Customer ID
12346.0    326
12347.0      2
12348.0     75
12349.0     19
12350.0    310
Name: InvoiceDate, dtype: int64

In [98]:
# Understand the distribution of Recency

recency.describe()

count    5878.000000
mean      201.331916
std       209.338707
min         1.000000
25%        26.000000
50%        96.000000
75%       380.000000
max       739.000000
Name: InvoiceDate, dtype: float64

# Frequency

In [99]:
# Count the number of unique invoices for each customer

frequency = df_clean.groupby('Customer ID')['Invoice'].nunique()

frequency.head()

Customer ID
12346.0    12
12347.0     8
12348.0     5
12349.0     4
12350.0     1
Name: Invoice, dtype: int64

In [100]:
# Understand the distribution of Frequency

frequency.describe()

count    5878.000000
mean        6.289384
std        13.009406
min         1.000000
25%         1.000000
50%         3.000000
75%         7.000000
max       398.000000
Name: Invoice, dtype: float64

# Monetary

In [101]:
# Calculate total spending for each customer

monetary = df_clean.groupby('Customer ID')['Revenue'].sum()

monetary.head()

Customer ID
12346.0    77556.46
12347.0     4921.53
12348.0     2019.40
12349.0     4428.69
12350.0      334.40
Name: Revenue, dtype: float64

In [102]:
# Understand the distribution of customer spending

monetary.describe()

count      5878.000000
mean       2955.904095
std       14440.852688
min           2.950000
25%         342.280000
50%         867.740000
75%        2248.305000
max      580987.040000
Name: Revenue, dtype: float64

# RFM

In [103]:
# Combine Recency, Frequency and Monetary into one table

rfm = pd.DataFrame({
    'Recency': recency,
    'Frequency': frequency,
    'Monetary': monetary
})

rfm.head()

             Recency  Frequency  Monetary
Customer ID
12346.0          326         12  77556.46
12347.0            2          8   4921.53
12348.0           75          5   2019.40
12349.0           19          4   4428.69
12350.0          310          1    334.40

In [104]:
rfm.shape

(5878, 3)

In [105]:
rfm.describe()

           Recency    Frequency       Monetary
count  5878.000000  5878.000000    5878.000000
mean    201.331916     6.289384    2955.904095
std     209.338707    13.009406   14440.852688
min       1.000000     1.000000       2.950000
25%      26.000000     1.000000     342.280000
50%      96.000000     3.000000     867.740000
75%     380.000000     7.000000    2248.305000
max     739.000000   398.000000  580987.040000

In [106]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency'],
    5,
    labels=[5, 4, 3, 2, 1]
)

rfm[['Recency', 'R_Score']].head(10)

             Recency R_Score
Customer ID
12346.0          326       2
12347.0            2       5
12348.0           75       3
12349.0           19       5
12350.0          310       2
12351.0          375       2
12352.0           36       4
12353.0          204       2
12354.0          232       2
12355.0          214       2

In [108]:
rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    5,
    labels=[1, 2, 3, 4, 5]
)

rfm[['Frequency', 'F_Score']].head(10)

             Frequency F_Score
Customer ID
12346.0             12       5
12347.0              8       4
12348.0              5       4
12349.0              4       3
12350.0              1       1
12351.0              1       1
12352.0             10       5
12353.0              2       2
12354.0              1       1
12355.0              2       2

In [109]:
rfm['M_Score'] = pd.qcut(
    rfm['Monetary'],
    5,
    labels=[1, 2, 3, 4, 5]
)

rfm[['Monetary', 'M_Score']].head(10)

             Monetary M_Score
Customer ID
12346.0      77556.46       5
12347.0       4921.53       5
12348.0       2019.40       4
12349.0       4428.69       5
12350.0        334.40       2
12351.0        300.93       2
12352.0       2849.84       4
12353.0        406.76       2
12354.0       1079.40       3
12355.0        947.61       3

In [110]:
# Create the RFM code, e.g. 255 = R:2, F:5, M:5

rfm['RFM_Code'] = (
    rfm['R_Score'].astype(str) +
    rfm['F_Score'].astype(str) +
    rfm['M_Score'].astype(str)
)

# Calculate the total RFM score

rfm['RFM_Score'] = (
    rfm['R_Score'].astype(int) +
    rfm['F_Score'].astype(int) +
    rfm['M_Score'].astype(int)
)

rfm.head(10)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code,RFM_Score
Customer ID,,,,,,,,
12346.0,326,12,77556.46,2,5,5,255,12
12347.0,2,8,4921.53,5,4,5,545,14
12348.0,75,5,2019.40,3,4,4,344,11
12349.0,19,4,4428.69,5,3,5,535,13
12350.0,310,1,334.40,2,1,2,212,5
12351.0,375,1,300.93,2,1,2,212,5
12352.0,36,10,2849.84,4,5,4,454,13
12353.0,204,2,406.76,2,2,2,222,6
12354.0,232,1,1079.40,2,1,3,213,6
12355.0,214,2,947.61,2,2,3,223,7

In [111]:
rfm[['R_Score', 'F_Score', 'M_Score', 'RFM_Code', 'RFM_Score']].describe()

         RFM_Score
count  5878.000000
mean      9.005104
std       3.643923
min       3.000000
25%       6.000000
50%       9.000000
75%      12.000000
max      15.000000

In [112]:
rfm['R_Score'].value_counts().sort_index()

R_Score
5    1188
4    1176
3    1167
2    1172
1    1175
Name: count, dtype: int64

In [113]:
rfm['F_Score'].value_counts().sort_index()

F_Score
1    1176
2    1175
3    1176
4    1175
5    1176
Name: count, dtype: int64

In [114]:
rfm['M_Score'].value_counts().sort_index()

M_Score
1    1176
2    1175
3    1176
4    1175
5    1176
Name: count, dtype: int64

In [115]:
rfm['RFM_Code'].value_counts().head(20)

RFM_Code
555    469
111    317
455    248
121    172
211    165
344    164
112    152
444    147
122    135
544    131
355    131
221    122
222    119
233    110
333    106
433    104
232    100
212     98
554     96
311     93
Name: count, dtype: int64

In [116]:
rfm.sort_values(
    ['R_Score', 'F_Score', 'M_Score'],
    ascending=False
).head(20)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code,RFM_Score
Customer ID,,,,,,,,
12482.0,576,29,23691.400,1,5,5,155,11
12835.0,428,41,5996.830,1,5,5,155,11
13446.0,430,11,3881.890,1,5,5,155,11
14063.0,438,9,22710.200,1,5,5,155,11
14249.0,411,12,5400.461,1,5,5,155,11
14590.0,425,20,2993.370,1,5,5,155,11
14648.0,416,15,4466.650,1,5,5,155,11
15369.0,492,11,6251.260,1,5,5,155,11
15633.0,509,13,4335.960,1,5,5,155,11
17032.0,548,8,2984.320,1,5,5,155,11
17448.0,497,46,14523.670,1,5,5,155,11
12986.0,429,10,2729.840,1,5,4,154,10
15013.0,488,10,1610.820,1,5,4,154,10
15015.0,501,13,2354.970,1,5,4,154,10
15751.0,461,11,1380.440,1,5,4,154,10
16197.0,469,9,2016.710,1,5,4,154,10
16158.0,522,9,628.320,1,5,3,153,9
13214.0,418,7,3264.230,1,4,5,145,10
13902.0,632,5,34095.260,1,4,5,145,10
14025.0,465,8,4057.900,1,4,5,145,10

In [117]:
rfm.sort_values(
    ['R_Score', 'F_Score', 'M_Score'],
    ascending=True
).head(20)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code,RFM_Score
Customer ID,,,,,,,,
12367.0,4,1,168.90,5,1,1,511,7
12442.0,3,1,172.06,5,1,1,511,7
12558.0,8,1,269.96,5,1,1,511,7
12587.0,8,1,144.00,5,1,1,511,7
12660.0,11,1,245.10,5,1,1,511,7
12966.0,10,1,160.18,5,1,1,511,7
12984.0,19,1,97.50,5,1,1,511,7
13017.0,7,1,204.00,5,1,1,511,7
13188.0,11,1,114.60,5,1,1,511,7
13322.0,17,1,199.48,5,1,1,511,7
13349.0,11,1,247.32,5,1,1,511,7
13436.0,2,1,196.89,5,1,1,511,7
13560.0,7,1,171.42,5,1,1,511,7
13638.0,16,1,122.64,5,1,1,511,7
14300.0,19,1,43.20,5,1,1,511,7
14349.0,10,1,133.50,5,1,1,511,7
14578.0,3,1,168.63,5,1,1,511,7
14601.0,11,1,213.96,5,1,1,511,7
14860.0,19,1,170.32,5,1,1,511,7
14946.0,14,1,100.90,5,1,1,511,7

In [118]:
rfm.sort_values(
    'RFM_Score',
    ascending=False
).head(20)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code,RFM_Score
Customer ID,,,,,,,,
18272.0,3,9,4385.98,5,5,5,555,15
12362.0,3,11,5356.23,5,5,5,555,15
13709.0,4,18,7571.35,5,5,5,555,15
13658.0,10,9,6025.50,5,5,5,555,15
13650.0,17,10,3288.00,5,5,5,555,15
13742.0,17,12,3107.87,5,5,5,555,15
16393.0,2,23,5297.77,5,5,5,555,15
16422.0,17,109,61920.87,5,5,5,555,15
17675.0,1,70,37642.48,5,5,5,555,15
17673.0,2,13,4173.88,5,5,5,555,15
17659.0,17,14,3586.99,5,5,5,555,15
13758.0,12,15,8698.13,5,5,5,555,15
13756.0,2,23,8655.95,5,5,5,555,15
13769.0,2,20,5478.12,5,5,5,555,15
13767.0,2,73,33903.57,5,5,5,555,15
13599.0,1,33,9811.04,5,5,5,555,15
13784.0,10,14,2910.23,5,5,5,555,15
13777.0,1,61,49638.26,5,5,5,555,15
17655.0,11,9,2976.38,5,5,5,555,15
16525.0,2,48,24151.30,5,5,5,555,15

In [119]:
rfm.sort_values(
    'RFM_Score',
    ascending=True
).head(20)

,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Code,RFM_Score
Customer ID,,,,,,,,
14635.0,454,1,215.22,1,1,1,111,3
15455.0,598,1,38.25,1,1,1,111,3
15479.0,733,1,147.40,1,1,1,111,3
14074.0,623,1,219.40,1,1,1,111,3
12692.0,637,1,110.95,1,1,1,111,3
15409.0,721,1,131.25,1,1,1,111,3
15474.0,596,1,150.35,1,1,1,111,3
15470.0,576,1,63.42,1,1,1,111,3
14033.0,555,1,109.44,1,1,1,111,3
15499.0,724,1,158.65,1,1,1,111,3
15496.0,631,1,146.14,1,1,1,111,3
15490.0,430,1,210.85,1,1,1,111,3
15487.0,680,1,231.32,1,1,1,111,3
15486.0,527,1,102.00,1,1,1,111,3
15548.0,596,1,158.09,1,1,1,111,3
15575.0,620,1,30.10,1,1,1,111,3
13222.0,577,1,88.50,1,1,1,111,3
13219.0,618,1,76.23,1,1,1,111,3
13241.0,412,1,112.53,1,1,1,111,3
13257.0,436,1,149.75,1,1,1,111,3

In [120]:
# Count customers with high scores across all three dimensions

champions = rfm[
    (rfm['R_Score'] >= 4) &
    (rfm['F_Score'] >= 4) &
    (rfm['M_Score'] >= 4)
]

champions.shape

(1183, 8)

In [121]:
# Customers who are less recent but have strong historical frequency or spending

at_risk = rfm[
    (rfm['R_Score'] <= 2) &
    (
        (rfm['F_Score'] >= 4) |
        (rfm['M_Score'] >= 4)
    )
]

at_risk.shape

(2610, 8)

In [122]:
# Recent customers with relatively low frequency and spending

potential = rfm[
    (rfm['R_Score'] >= 4) &
    (rfm['F_Score'] <= 2) &
    (rfm['M_Score'] <= 2)
]

potential.shape

(1760, 8)

In [123]:
# Low engagement and low spending

inactive = rfm[
    (rfm['R_Score'] <= 2) &
    (rfm['F_Score'] <= 2) &
    (rfm['M_Score'] <= 2)
]

inactive.shape

(1099, 8)

In [124]:
# Create flags for each candidate segment

rfm['Champions_Flag'] = (
    (rfm['R_Score'] >= 4) &
    (rfm['F_Score'] >= 4) &
    (rfm['M_Score'] >= 4)
)

rfm['At_Risk_Flag'] = (
    (rfm['R_Score'] <= 2) &
    (
        (rfm['F_Score'] >= 4) |
        (rfm['M_Score'] >= 4)
    )
)

rfm['Potential_Flag'] = (
    (rfm['R_Score'] >= 4) &
    (rfm['F_Score'] <= 2) &
    (rfm['M_Score'] <= 2)
)

rfm['Inactive_Flag'] = (
    (rfm['R_Score'] <= 2) &
    (rfm['F_Score'] <= 2) &
    (rfm['M_Score'] <= 2)
)

# Count how many segment conditions each customer satisfies

rfm['Segment_Count'] = (
    rfm['Champions_Flag'].astype(int) +
    rfm['At_Risk_Flag'].astype(int) +
    rfm['Potential_Flag'].astype(int) +
    rfm['Inactive_Flag'].astype(int)
)

rfm['Segment_Count'].value_counts().sort_index()

Segment_Count
0    1333
1    2438
2    2107
Name: count, dtype: int64

In [125]:
def assign_segment(row):

    R = row['R_Score']
    F = row['F_Score']
    M = row['M_Score']

    # 1. Champions
    if R >= 4 and F >= 4 and M >= 4:
        return 'Champions'

    # 2. At Risk
    elif R <= 2 and (F >= 4 or M >= 4):
        return 'At Risk'

    # 3. Potential Customers
    elif R >= 4 and F <= 2 and M <= 2:
        return 'Potential Customers'

    # 4. Inactive / Low Value
    elif R <= 2 and F <= 2 and M <= 2:
        return 'Inactive / Low Value'

    # 5. Remaining customers
    else:
        return 'Other Customers'


rfm['Segment'] = rfm.apply(assign_segment, axis=1)

In [126]:
rfm['Segment'].value_counts()

Segment
Other Customers         2460
Champions               1297
Inactive / Low Value    1280
At Risk                  525
Potential Customers      316
Name: count, dtype: int64

In [127]:
other = rfm[rfm['Segment'] == 'Other Customers']

other['RFM_Code'].value_counts().head(20)

RFM_Code
344    164
355    131
233    110
333    106
433    104
232    100
311     93
543     80
533     79
443     75
343     72
133     70
334     68
322     68
312     68
432     65
332     61
123     59
223     59
345     56
Name: count, dtype: int64

In [128]:
other[['R_Score', 'F_Score', 'M_Score', 'RFM_Score']].describe()

         RFM_Score
count  2460.000000
mean      9.073984
std       2.292777
min       5.000000
25%       7.000000
50%       9.000000
75%      11.000000
max      13.000000

In [129]:
rfm.groupby('Segment')[['Recency', 'Frequency', 'Monetary', 'RFM_Score']].mean().round(2)

                      Recency  Frequency  Monetary  RFM_Score
Segment
At Risk                361.30       5.96   2930.79       9.23
Champions               19.96      17.11   9143.86      13.91
Inactive / Low Value   467.32       1.19    253.03       4.22
Other Customers        146.64       3.95   1447.73       9.07
Potential Customers     28.29       1.33    288.74       7.36

In [130]:
def assign_segment(row):

    R = row['R_Score']
    F = row['F_Score']
    M = row['M_Score']

    # 1. Champions
    if R >= 4 and F >= 4 and M >= 4:
        return 'Champions'

    # 2. At Risk
    elif R <= 2 and (F >= 3 or M >= 3):
        return 'At Risk'

    # 3. Loyal Customers
    elif R >= 3 and F >= 4:
        return 'Loyal Customers'

    # 4. Potential Customers
    elif R >= 4 and F <= 2:
        return 'Potential Customers'

    # 5. Inactive / Low Value
    elif R <= 2 and F <= 2 and M <= 2:
        return 'Inactive / Low Value'

    # 6. Regular / Mid-Value
    else:
        return 'Regular / Mid-Value'


rfm['Segment'] = rfm.apply(assign_segment, axis=1)

In [131]:
rfm['Segment'].value_counts()

Segment
Champions               1297
Inactive / Low Value    1280
Regular / Mid-Value     1090
At Risk                 1067
Loyal Customers          701
Potential Customers      443
Name: count, dtype: int64

In [132]:
rfm.groupby('Segment')[[
    'Recency',
    'Frequency',
    'Monetary',
    'RFM_Score'
]].mean().round(2)

                      Recency  Frequency  Monetary  RFM_Score
Segment
At Risk                379.99       4.18   1799.37       7.96
Champions               19.96      17.11   9143.86      13.91
Inactive / Low Value   467.32       1.19    253.03       4.22
Loyal Customers         84.37       7.74   2648.60      11.46
Potential Customers     28.11       1.46    885.48       7.97
Regular / Mid-Value     75.52       2.51    938.04       8.66

In [133]:
pd.crosstab(
    rfm['R_Score'],
    rfm['Segment']
)

Segment,At Risk,Champions,Inactive / Low Value,Loyal Customers,Potential Customers,Regular / Mid-Value
R_Score,,,,,,
5,0,741,0,96,163,188
4,0,556,0,89,280,251
3,0,0,0,516,0,651
2,668,0,504,0,0,0
1,399,0,776,0,0,0

In [134]:
pd.crosstab(
    rfm['F_Score'],
    rfm['Segment']
)

Segment,At Risk,Champions,Inactive / Low Value,Loyal Customers,Potential Customers,Regular / Mid-Value
F_Score,,,,,,
1,84,0,732,0,168,192
2,159,0,548,0,275,193
3,471,0,0,0,0,705
4,282,398,0,495,0,0
5,71,899,0,206,0,0

In [135]:
segment_summary = rfm.groupby('Segment').agg(
    Customers=('Segment', 'size'),
    Total_Revenue=('Monetary', 'sum'),
    Avg_Revenue=('Monetary', 'mean'),
    Avg_Recency=('Recency', 'mean'),
    Avg_Frequency=('Frequency', 'mean')
).sort_values('Total_Revenue', ascending=False)

segment_summary

,Customers,Total_Revenue,Avg_Revenue,Avg_Recency,Avg_Frequency
Segment,,,,,
Champions,1297,1.185959e+07,9143.863913,19.961449,17.105628
At Risk,1067,1.919928e+06,1799.370106,379.991565,4.180881
Loyal Customers,701,1.856667e+06,2648.597753,84.368046,7.736091
Regular / Mid-Value,1090,1.022468e+06,938.043774,75.524771,2.508257
Potential Customers,443,3.922670e+05,885.478600,28.106095,1.460497
Inactive / Low Value,1280,3.238831e+05,253.033680,467.322656,1.185938

In [136]:
segment_summary['Customer_Share_%'] = (
    segment_summary['Customers'] /
    len(rfm) * 100
)

segment_summary['Revenue_Share_%'] = (
    segment_summary['Total_Revenue'] /
    rfm['Monetary'].sum() * 100
)

segment_summary.round(2)

,Customers,Total_Revenue,Avg_Revenue,Avg_Recency,Avg_Frequency,Customer_Share_%,Revenue_Share_%
Segment,,,,,,,
Champions,1297,11859591.50,9143.86,19.96,17.11,22.07,68.26
At Risk,1067,1919927.90,1799.37,379.99,4.18,18.15,11.05
Loyal Customers,701,1856667.02,2648.60,84.37,7.74,11.93,10.69
Regular / Mid-Value,1090,1022467.71,938.04,75.52,2.51,18.54,5.88
Potential Customers,443,392267.02,885.48,28.11,1.46,7.54,2.26
Inactive / Low Value,1280,323883.11,253.03,467.32,1.19,21.78,1.86

In [137]:
# Attach each customer's RFM segment to the transaction data

df_segmented = df_clean.merge(
    rfm[['Segment']],
    left_on='Customer ID',
    right_index=True,
    how='left'
)

df_segmented.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Segment
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,Loyal Customers
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,Loyal Customers
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,Loyal Customers
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,Loyal Customers
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,Loyal Customers

In [138]:
df_segmented.shape

(779425, 10)

In [139]:
df_segmented['Segment'].isna().sum()

np.int64(0)

In [140]:
segment_product_revenue = (
    df_segmented
    .groupby(['Segment', 'Description'])['Revenue']
    .sum()
    .reset_index()
    .sort_values(['Segment', 'Revenue'], ascending=[True, False])
)

segment_product_revenue.head(20)

      Segment                         Description   Revenue
2163  At Risk      MEDIUM CERAMIC TOP STORAGE JAR  77213.60
2299  At Risk                              Manual  55856.05
4019  At Risk  WHITE HANGING HEART T-LIGHT HOLDER  39446.45
3032  At Risk            REGENCY CAKESTAND 3 TIER  22236.60
1277  At Risk  FAIRY CAKE FLANNEL ASSORTED COLOUR  14966.25
2834  At Risk                             POSTAGE  10471.90
2907  At Risk              RED  HARMONICA IN BOX   10019.92
1130  At Risk                  DOORMAT FAIRY CAKE   9877.41
2474  At Risk     PAPER CHAIN KIT 50'S CHRISTMAS    9830.75
1557  At Risk         GIN + TONIC DIET METAL SIGN   9742.65
3453  At Risk    SET/4 WHITE RETRO STORAGE CUBES    9252.00
3949  At Risk          VINTAGE UNION JACK BUNTING   8744.50
237   At Risk       ASSORTED COLOUR BIRD ORNAMENT   7927.47
2504  At Risk                       PARTY BUNTING   7675.00
3697  At Risk      STRAWBERRY CERAMIC TRINKET BOX   7644.61
2673  At Risk         PINK HAPPY BIRTHDAY BUNTING   7400.75
3772  At Risk                TEA TIME TEA TOWELS    7249.70
2091  At Risk             LUNCH BAG  BLACK SKULL.   6963.55
1192  At Risk             EDWARDIAN PARASOL BLACK   6897.35
2930  At Risk    RED HANGING HEART T-LIGHT HOLDER   6773.10

In [142]:
top_products_by_segment = (
    segment_product_revenue
    .groupby('Segment')
    .head(10)
)

top_products_by_segment

                    Segment                         Description    Revenue
2163                At Risk      MEDIUM CERAMIC TOP STORAGE JAR   77213.60
2299                At Risk                              Manual   55856.05
4019                At Risk  WHITE HANGING HEART T-LIGHT HOLDER   39446.45
3032                At Risk            REGENCY CAKESTAND 3 TIER   22236.60
1277                At Risk  FAIRY CAKE FLANNEL ASSORTED COLOUR   14966.25
2834                At Risk                             POSTAGE   10471.90
2907                At Risk              RED  HARMONICA IN BOX    10019.92
1130                At Risk                  DOORMAT FAIRY CAKE    9877.41
2474                At Risk     PAPER CHAIN KIT 50'S CHRISTMAS     9830.75
1557                At Risk         GIN + TONIC DIET METAL SIGN    9742.65
7862              Champions            REGENCY CAKESTAND 3 TIER  215988.00
9117              Champions  WHITE HANGING HEART T-LIGHT HOLDER  168204.22
6517              Champions             JUMBO BAG RED RETROSPOT  104924.90
4481              Champions       ASSORTED COLOUR BIRD ORNAMENT   96181.89
7640              Champions                             POSTAGE   84020.80
7259              Champions                       PARTY BUNTING   70706.18
6973              Champions                              Manual   67249.65
5170              Champions                       CHILLI LIGHTS   58172.10
4686              Champions            BLACK RECORD COVER FRAME   54466.58
7227              Champions     PAPER CHAIN KIT 50'S CHRISTMAS    51453.33
12674  Inactive / Low Value  WHITE HANGING HEART T-LIGHT HOLDER    3804.00
11840  Inactive / Low Value            REGENCY CAKESTAND 3 TIER    2897.10
11665  Inactive / Low Value                             POSTAGE    2334.00
9555   Inactive / Low Value       ASSORTED COLOUR BIRD ORNAMENT    1766.05
10355  Inactive / Low Value           EDWARDIAN PARASOL NATURAL    1670.45
10709  Inactive / Low Value               GRAND CHOCOLATECANDLE    1644.90
11246  Inactive / Low Value                              Manual    1590.09
9616   Inactive / Low Value       BAKING SET 9 PIECE RETROSPOT     1569.15
11411  Inactive / Low Value                       PARTY BUNTING    1538.75
9531   Inactive / Low Value   ANTIQUE SILVER TEA GLASS ENGRAVED    1401.28
17211       Loyal Customers  WHITE HANGING HEART T-LIGHT HOLDER   26446.09
16062       Loyal Customers            REGENCY CAKESTAND 3 TIER   24369.40
15525       Loyal Customers                       PARTY BUNTING   17666.65
14876       Loyal Customers             JUMBO BAG RED RETROSPOT   16795.74
15287       Loyal Customers                              Manual   12382.75
16548       Loyal Customers    SET/4 WHITE RETRO STORAGE CUBES    11413.80
13070       Loyal Customers       ASSORTED COLOUR BIRD ORNAMENT   10777.04
15735       Loyal Customers                 PINK PAPER PARASOL     9152.15
17121       Loyal Customers          VINTAGE UNION JACK BUNTING    8908.00
15858       Loyal Customers                             POSTAGE    7683.40
19026   Potential Customers         PAPER CRAFT , LITTLE BIRDIE  168469.60
19217   Potential Customers                             POSTAGE    4704.00
18805   Potential Customers     METAL SIGN TAKE IT OR LEAVE IT     3981.95
19346   Potential Customers            REGENCY CAKESTAND 3 TIER    2860.05
19990   Potential Customers        VINTAGE DOILY JUMBO BAG RED     2747.40
17568   Potential Customers       ASSORTED COLOUR BIRD ORNAMENT    1721.36
17601   Potential Customers       BAKING SET 9 PIECE RETROSPOT     1456.35
17602   Potential Customers          BAKING SET SPACEBOY DESIGN    1411.05
19019   Potential Customers     PAPER CHAIN KIT 50'S CHRISTMAS     1245.35
19233   Potential Customers                  RABBIT NIGHT LIGHT    1049.36
22613   Regular / Mid-Value      PICNIC BASKET WICKER 60 PIECES   39619.50
22826   Regular / Mid-Value                             POSTAGE   15433.94
22344   Regular / Mid-Value                              Manual   14656.75
23013   Regular / Mid-Value            REGENCY CAKESTAND 3 TIER    9305.10
24019   Regular / Mid-Value  WHITE HANGING HEART T-LIGHT HOLDER    8471.70
22865   Regular / Mid-Value                  RABBIT NIGHT LIGHT    8182.02
22531   Regular / Mid-Value     PAPER CHAIN KIT 50'S CHRISTMAS     6975.20
20414   Regular / Mid-Value       ASSORTED COLOUR BIRD ORNAMENT    5978.05
21997   Regular / Mid-Value             JUMBO BAG RED RETROSPOT    5353.61
22558   Regular / Mid-Value                       PARTY BUNTING    4807.70

In [143]:
df_products = df_segmented[
    ~df_segmented['Description'].isin(['POSTAGE', 'Manual'])
].copy()

In [144]:
df_products['Description'].isin(['POSTAGE', 'Manual']).sum()

np.int64(0)

In [145]:
segment_product_analysis = (
    df_products
    .groupby(['Segment', 'Description'])
    .agg(
        Revenue=('Revenue', 'sum'),
        Quantity=('Quantity', 'sum'),
        Customers=('Customer ID', 'nunique')
    )
    .reset_index()
)

segment_product_analysis.head()

   Segment                          Description  Revenue  Quantity  Customers
0  At Risk    DOORMAT UNION JACK GUNS AND ROSES   228.25        35         12
1  At Risk             3 STRIPEY MICE FELTCRAFT   243.75       125         24
2  At Risk        4 PURPLE FLOCK DINNER CANDLES    56.10        46          4
3  At Risk                      ANIMAL STICKERS    15.12        72          2
4  At Risk          BLACK PIRATE TREASURE CHEST    23.10        14          1

In [146]:
top_products_by_segment = (
    segment_product_analysis
    .sort_values(
        ['Segment', 'Revenue'],
        ascending=[True, False]
    )
    .groupby('Segment')
    .head(10)
)

top_products_by_segment

,Segment,Description,Revenue,Quantity,Customers
2163,At Risk,MEDIUM CERAMIC TOP STORAGE JAR,77213.60,74239,3
4017,At Risk,WHITE HANGING HEART T-LIGHT HOLDER,39446.45,14941,316
3030,At Risk,REGENCY CAKESTAND 3 TIER,22236.60,1892,226
1277,At Risk,FAIRY CAKE FLANNEL ASSORTED COLOUR,14966.25,6992,60
2905,At Risk,RED HARMONICA IN BOX,10019.92,9252,57
1130,At Risk,DOORMAT FAIRY CAKE,9877.41,1487,35
2473,At Risk,PAPER CHAIN KIT 50'S CHRISTMAS,9830.75,3733,113
1557,At Risk,GIN + TONIC DIET METAL SIGN,9742.65,5257,101
3451,At Risk,SET/4 WHITE RETRO STORAGE CUBES,9252.00,260,28
3947,At Risk,VINTAGE UNION JACK BUNTING,8744.50,1072,121
7858,Champions,REGENCY CAKESTAND 3 TIER,215988.00,18927,531
9113,Champions,WHITE HANGING HEART T-LIGHT HOLDER,168204.22,62572,545
6515,Champions,JUMBO BAG RED RETROSPOT,104924.90,58130,432
4479,Champions,ASSORTED COLOUR BIRD ORNAMENT,96181.89,61125,425
7256,Champions,PARTY BUNTING,70706.18,16204,392
5168,Champions,CHILLI LIGHTS,58172.10,12503,162
4684,Champions,BLACK RECORD COVER FRAME,54466.58,15931,109
7224,Champions,PAPER CHAIN KIT 50'S CHRISTMAS,51453.33,19073,419
6520,Champions,JUMBO BAG STRAWBERRY,51290.15,28876,277
7999,Champions,ROTATING SILVER ANGELS T-LIGHT HLDR,49799.02,26073,144
12668,Inactive / Low Value,WHITE HANGING HEART T-LIGHT HOLDER,3804.00,1312,182
11834,Inactive / Low Value,REGENCY CAKESTAND 3 TIER,2897.10,234,88
9551,Inactive / Low Value,ASSORTED COLOUR BIRD ORNAMENT,1766.05,1045,76
10351,Inactive / Low Value,EDWARDIAN PARASOL NATURAL,1670.45,311,43
10705,Inactive / Low Value,GRAND CHOCOLATECANDLE,1644.90,1194,58
9612,Inactive / Low Value,BAKING SET 9 PIECE RETROSPOT,1569.15,317,94
11406,Inactive / Low Value,PARTY BUNTING,1538.75,329,58
9527,Inactive / Low Value,ANTIQUE SILVER TEA GLASS ENGRAVED,1401.28,1256,31
9528,Inactive / Low Value,ANTIQUE SILVER TEA GLASS ETCHED,1074.10,914,42
11741,Inactive / Low Value,RED HANGING HEART T-LIGHT HOLDER,1059.05,359,66
17203,Loyal Customers,WHITE HANGING HEART T-LIGHT HOLDER,26446.09,9649,236
16054,Loyal Customers,REGENCY CAKESTAND 3 TIER,24369.40,2070,212
15518,Loyal Customers,PARTY BUNTING,17666.65,3983,165
14870,Loyal Customers,JUMBO BAG RED RETROSPOT,16795.74,9284,136
16540,Loyal Customers,SET/4 WHITE RETRO STORAGE CUBES,11413.80,324,17
13064,Loyal Customers,ASSORTED COLOUR BIRD ORNAMENT,10777.04,6536,141
15728,Loyal Customers,PINK PAPER PARASOL,9152.15,3577,18
17113,Loyal Customers,VINTAGE UNION JACK BUNTING,8908.00,1048,105
14868,Loyal Customers,JUMBO BAG PINK VINTAGE PAISLEY,7569.85,4141,84
13076,Loyal Customers,ASSORTED COLOURS SILK FAN,7286.76,10836,52
19017,Potential Customers,"PAPER CRAFT , LITTLE BIRDIE",168469.60,80995,1
18797,Potential Customers,METAL SIGN TAKE IT OR LEAVE IT,3981.95,1445,12
19336,Potential Customers,REGENCY CAKESTAND 3 TIER,2860.05,239,56
19980,Potential Customers,VINTAGE DOILY JUMBO BAG RED,2747.40,1530,9
17560,Potential Customers,ASSORTED COLOUR BIRD ORNAMENT,1721.36,1064,52
17593,Potential Customers,BAKING SET 9 PIECE RETROSPOT,1456.35,301,64
17594,Potential Customers,BAKING SET SPACEBOY DESIGN,1411.05,319,27
19010,Potential Customers,PAPER CHAIN KIT 50'S CHRISTMAS,1245.35,433,59
19223,Potential Customers,RABBIT NIGHT LIGHT,1049.36,548,45
18083,Potential Customers,DOORMAT KEEP CALM AND COME IN,1003.65,133,24
22602,Regular / Mid-Value,PICNIC BASKET WICKER 60 PIECES,39619.50,61,1
23001,Regular / Mid-Value,REGENCY CAKESTAND 3 TIER,9305.10,762,201
24007,Regular / Mid-Value,WHITE HANGING HEART T-LIGHT HOLDER,8471.70,3054,173
22853,Regular / Mid-Value,RABBIT NIGHT LIGHT,8182.02,4500,77
22520,Regular / Mid-Value,PAPER CHAIN KIT 50'S CHRISTMAS,6975.20,2576,131
20404,Regular / Mid-Value,ASSORTED COLOUR BIRD ORNAMENT,5978.05,3613,158
21987,Regular / Mid-Value,JUMBO BAG RED RETROSPOT,5353.61,2861,115
22547,Regular / Mid-Value,PARTY BUNTING,4807.70,1040,121
22341,Regular / Mid-Value,NATURAL SLATE HEART CHALKBOARD,4264.00,1536,124
20463,Regular / Mid-Value,BAKING SET 9 PIECE RETROSPOT,4023.45,823,187

In [147]:
segment_product_analysis['Revenue_per_Customer'] = (
    segment_product_analysis['Revenue'] /
    segment_product_analysis['Customers']
)

In [148]:
top_revenue_per_customer = (
    segment_product_analysis
    .sort_values(
        ['Segment', 'Revenue_per_Customer'],
        ascending=[True, False]
    )
    .groupby('Segment')
    .head(10)
)

top_revenue_per_customer

,Segment,Description,Revenue,Quantity,Customers,Revenue_per_Customer
2163,At Risk,MEDIUM CERAMIC TOP STORAGE JAR,77213.60,74239,3,25737.866667
3589,At Risk,SMALL FAIRY CAKE FRIDGE MAGNETS,6507.20,11984,2,3253.600000
3179,At Risk,S/16 VINTAGE RED CUTLERY,1314.00,120,1,1314.000000
1998,At Risk,LARGE HANGING GLASS+ZINC LANTERN,896.00,560,1,896.000000
375,At Risk,BLACK AND WHITE PAISLEY FLOWER MUG,2568.90,25206,5,513.780000
3741,At Risk,SWISS ROLL TOWEL PINK SPOTS,510.00,200,1,510.000000
2011,At Risk,LARGE RED SPOT WINDMILL,4435.20,2392,9,492.800000
360,At Risk,BIRD IN TREE MUG,460.80,4608,1,460.800000
3901,At Risk,VINTAGE BLUE KITCHEN CABINET,1180.00,4,3,393.333333
2814,At Risk,POP-ART FLUORESCENT PENS,368.64,6144,1,368.640000
5561,Champions,DOTCOM POSTAGE,11906.36,16,1,11906.360000
6900,Champions,"MIRROR, ARCHED GEORGIAN",3884.00,200,1,3884.000000
5692,Champions,ENGLISH ROSE EDWARDIAN PARASOL,1515.00,505,1,1515.000000
5050,Champions,CARRIAGE,9685.00,191,8,1210.625000
6151,Champions,GOLD WINE GLASS,998.82,294,1,998.820000
6914,Champions,MISELTOE HEART WREATH CREAM,996.00,240,1,996.000000
4726,Champions,BLUE 5 PATCH FLOWER CUSHION COVER,748.80,384,1,748.800000
9336,Champions,ZINC POLICE BOX LANTERN,748.00,187,1,748.000000
4686,Champions,BLACK RETRODISC LAMPSHADE,1717.95,881,3,572.650000
7469,Champions,PINK KASHMIRI COFFEE TABLE,1050.00,20,2,525.000000
10011,Inactive / Low Value,CHEST NATURAL WOOD 20 DRAWERS,660.00,6,2,330.000000
10632,Inactive / Low Value,GIANT SEVENTEEN DRAWER SIDEBOARD,290.00,2,1,290.000000
9388,Inactive / Low Value,16 PIECE CUTLERY SET PANTRY DESIGN,255.20,16,1,255.200000
9480,Inactive / Low Value,AFGHAN SLIPPER SOCK PAIR,686.60,228,3,228.866667
11076,Inactive / Low Value,LOVE SEAT ANTIQUE WHITE METAL,195.00,1,1,195.000000
12602,Inactive / Low Value,VINTAGE RED KITCHEN CABINET,375.00,3,2,187.500000
11952,Inactive / Low Value,RUSTIC SEVENTEEN DRAWER SIDEBOARD,165.00,1,1,165.000000
12601,Inactive / Low Value,VINTAGE POST OFFICE CABINET,659.55,9,4,164.887500
12572,Inactive / Low Value,VINTAGE BLUE KITCHEN CABINET,125.00,1,1,125.000000
12301,Inactive / Low Value,SMALL CHINESE STYLE SCISSOR,362.42,1101,3,120.806667
16540,Loyal Customers,SET/4 WHITE RETRO STORAGE CUBES,11413.80,324,17,671.400000
16397,Loyal Customers,SET OF 36 DOILIES VINTAGE CHRISTMAS,540.00,432,1,540.000000
15728,Loyal Customers,PINK PAPER PARASOL,9152.15,3577,18,508.452778
16751,Loyal Customers,SOMBRERO,4559.85,3523,11,414.531818
13456,Loyal Customers,BROWN COZY SQUARE PHOTO ALBUM,399.75,205,1,399.750000
17046,Loyal Customers,VINTAGE BLUE KITCHEN CABINET,2225.00,11,6,370.833333
16680,Loyal Customers,SMALL CHINESE STYLE SCISSOR,2897.22,9041,8,362.152500
16581,Loyal Customers,SHAKER THROW QUILTED,658.80,40,2,329.400000
14105,Loyal Customers,EMPIRE DESIGN ROSETTE,3350.42,4024,11,304.583636
13111,Loyal Customers,Adjustment by Peter on Jun 25 2010,300.13,1,1,300.130000
19017,Potential Customers,"PAPER CRAFT , LITTLE BIRDIE",168469.60,80995,1,168469.600000
17852,Potential Customers,CHEST NATURAL WOOD 20 DRAWERS,440.00,4,1,440.000000
18797,Potential Customers,METAL SIGN TAKE IT OR LEAVE IT,3981.95,1445,12,331.829167
19980,Potential Customers,VINTAGE DOILY JUMBO BAG RED,2747.40,1530,9,305.266667
19437,Potential Customers,RUSTIC SEVENTEEN DRAWER SIDEBOARD,290.00,2,1,290.000000
18331,Potential Customers,GIANT SEVENTEEN DRAWER SIDEBOARD,165.00,1,1,165.000000
19168,Potential Customers,PINK/PURPLE RETRO RADIO,159.30,54,1,159.300000
18435,Potential Customers,HANGING BAUBLE T-LIGHT HOLDER SMALL,154.50,71,1,154.500000
17662,Potential Customers,BLUE 3 PIECE MINI DOTS CUTLERY SET,266.58,78,2,133.290000
19096,Potential Customers,PINK 3 PIECE MINI DOTS CUTLERY SET,266.58,78,2,133.290000
22602,Regular / Mid-Value,PICNIC BASKET WICKER 60 PIECES,39619.50,61,1,39619.500000
23140,Regular / Mid-Value,RUSTIC SEVENTEEN DRAWER SIDEBOARD,455.00,3,1,455.000000
22142,Regular / Mid-Value,LOVE SEAT ANTIQUE WHITE METAL,1810.00,20,6,301.666667
23916,Regular / Mid-Value,VINTAGE RED KITCHEN CABINET,545.00,3,2,272.500000
23003,Regular / Mid-Value,REGENCY MIRROR WITH SHUTTERS,745.00,5,3,248.333333
20447,Regular / Mid-Value,Adjustment by john on 26/01/2010 17,243.63,1,1,243.630000
23869,Regular / Mid-Value,VINTAGE BLUE KITCHEN CABINET,935.00,4,4,233.750000
21296,Regular / Mid-Value,ECONOMY PASSPORT COVER,231.00,110,1,231.000000
20443,Regular / Mid-Value,ASSTD DESIGN POP ART SLIM PEN,204.00,240,1,204.000000
20372,Regular / Mid-Value,ANTIQUE HEART SHELF UNIT,2202.30,162,12,183.525000

In [149]:
top_products_by_customer_reach = (
    segment_product_analysis
    .sort_values(
        ['Segment', 'Customers', 'Revenue'],
        ascending=[True, False, False]
    )
    .groupby('Segment')
    .head(10)
)

top_products_by_customer_reach

,Segment,Description,Revenue,Quantity,Customers,Revenue_per_Customer
4017,At Risk,WHITE HANGING HEART T-LIGHT HOLDER,39446.45,14941,316,124.830538
3030,At Risk,REGENCY CAKESTAND 3 TIER,22236.60,1892,226,98.392035
300,At Risk,BAKING SET 9 PIECE RETROSPOT,5050.20,1044,192,26.303125
3695,At Risk,STRAWBERRY CERAMIC TRINKET BOX,7644.61,6641,166,46.051867
237,At Risk,ASSORTED COLOUR BIRD ORNAMENT,7927.47,4851,158,50.173861
1818,At Risk,HOME BUILDING BLOCK WORD,5879.55,999,158,37.212342
1787,At Risk,HEART OF WICKER SMALL,4971.25,3169,156,31.866987
128,At Risk,60 TEATIME FAIRY CAKE CASES,3322.90,6694,156,21.300641
2928,At Risk,RED HANGING HEART T-LIGHT HOLDER,6773.10,2466,153,44.268627
1786,At Risk,HEART OF WICKER LARGE,5596.45,1963,150,37.309667
9113,Champions,WHITE HANGING HEART T-LIGHT HOLDER,168204.22,62572,545,308.631596
7858,Champions,REGENCY CAKESTAND 3 TIER,215988.00,18927,531,406.757062
4553,Champions,BAKING SET 9 PIECE RETROSPOT,26443.11,5591,442,59.826041
6515,Champions,JUMBO BAG RED RETROSPOT,104924.90,58130,432,242.881713
4479,Champions,ASSORTED COLOUR BIRD ORNAMENT,96181.89,61125,425,226.310329
7224,Champions,PAPER CHAIN KIT 50'S CHRISTMAS,51453.33,19073,419,122.800310
6331,Champions,HEART OF WICKER SMALL,31117.29,18560,397,78.381083
6741,Champions,LUNCH BAG SPACEBOY DESIGN,20699.55,12951,395,52.403924
7256,Champions,PARTY BUNTING,70706.18,16204,392,180.372908
7171,Champions,PACK OF 72 RETROSPOT CAKE CASES,13935.26,28540,388,35.915619
12668,Inactive / Low Value,WHITE HANGING HEART T-LIGHT HOLDER,3804.00,1312,182,20.901099
11893,Inactive / Low Value,REX CASH+CARRY JUMBO SHOPPER,219.45,231,102,2.151471
9612,Inactive / Low Value,BAKING SET 9 PIECE RETROSPOT,1569.15,317,94,16.693085
11834,Inactive / Low Value,REGENCY CAKESTAND 3 TIER,2897.10,234,88,32.921591
9551,Inactive / Low Value,ASSORTED COLOUR BIRD ORNAMENT,1766.05,1045,76,23.237500
11741,Inactive / Low Value,RED HANGING HEART T-LIGHT HOLDER,1059.05,359,66,16.046212
10817,Inactive / Low Value,HEART OF WICKER LARGE,802.40,272,60,13.373333
10705,Inactive / Low Value,GRAND CHOCOLATECANDLE,1644.90,1194,58,28.360345
11406,Inactive / Low Value,PARTY BUNTING,1538.75,329,58,26.530172
12609,Inactive / Low Value,VINTAGE SNAP CARDS,488.75,575,57,8.574561
17203,Loyal Customers,WHITE HANGING HEART T-LIGHT HOLDER,26446.09,9649,236,112.059703
16054,Loyal Customers,REGENCY CAKESTAND 3 TIER,24369.40,2070,212,114.950000
15518,Loyal Customers,PARTY BUNTING,17666.65,3983,165,107.070606
13127,Loyal Customers,BAKING SET 9 PIECE RETROSPOT,4528.65,959,158,28.662342
15287,Loyal Customers,NATURAL SLATE HEART CHALKBOARD,6372.35,2261,149,42.767450
13064,Loyal Customers,ASSORTED COLOUR BIRD ORNAMENT,10777.04,6536,141,76.432908
14706,Loyal Customers,HEART OF WICKER SMALL,4148.10,2578,141,29.419149
12954,Loyal Customers,60 TEATIME FAIRY CAKE CASES,5935.26,13264,139,42.699712
14705,Loyal Customers,HEART OF WICKER LARGE,5006.45,1747,137,36.543431
14870,Loyal Customers,JUMBO BAG RED RETROSPOT,16795.74,9284,136,123.498088
17593,Potential Customers,BAKING SET 9 PIECE RETROSPOT,1456.35,301,64,22.755469
19010,Potential Customers,PAPER CHAIN KIT 50'S CHRISTMAS,1245.35,433,59,21.107627
19336,Potential Customers,REGENCY CAKESTAND 3 TIER,2860.05,239,56,51.072321
17560,Potential Customers,ASSORTED COLOUR BIRD ORNAMENT,1721.36,1064,52,33.103077
18529,Potential Customers,HOT WATER BOTTLE KEEP CALM,871.80,180,47,18.548936
20101,Potential Customers,WOODEN HEART CHRISTMAS SCANDINAVIAN,335.58,1134,47,7.140000
20108,Potential Customers,WOODEN STAR CHRISTMAS SCANDINAVIAN,261.32,820,47,5.560000
19223,Potential Customers,RABBIT NIGHT LIGHT,1049.36,548,45,23.319111
19387,Potential Customers,REX CASH+CARRY JUMBO SHOPPER,80.75,85,45,1.794444
20006,Potential Customers,VINTAGE SNAP CARDS,453.88,556,40,11.347000
23001,Regular / Mid-Value,REGENCY CAKESTAND 3 TIER,9305.10,762,201,46.294030
20463,Regular / Mid-Value,BAKING SET 9 PIECE RETROSPOT,4023.45,823,187,21.515775
24007,Regular / Mid-Value,WHITE HANGING HEART T-LIGHT HOLDER,8471.70,3054,173,48.969364
20404,Regular / Mid-Value,ASSORTED COLOUR BIRD ORNAMENT,5978.05,3613,158,37.835759
22520,Regular / Mid-Value,PAPER CHAIN KIT 50'S CHRISTMAS,6975.20,2576,131,53.245802
23270,Regular / Mid-Value,SET OF 3 CAKE TINS PANTRY DESIGN,2779.05,575,130,21.377308
22341,Regular / Mid-Value,NATURAL SLATE HEART CHALKBOARD,4264.00,1536,124,34.387097
23071,Regular / Mid-Value,REX CASH+CARRY JUMBO SHOPPER,389.50,410,124,3.141129
22547,Regular / Mid-Value,PARTY BUNTING,4807.70,1040,121,39.733058
20293,Regular / Mid-Value,6 RIBBONS RUSTIC CHARM,2733.60,1588,120,22.780000

In [150]:
segment_summary = (
    df_segmented.groupby('Segment')
    .agg(
        Customers=('Customer ID', 'nunique'),
        Revenue=('Revenue', 'sum'),
        Orders=('Invoice', 'nunique'),
        Recency=('Customer ID', lambda x: rfm.loc[x.unique(), 'Recency'].mean()),
        Frequency=('Customer ID', lambda x: rfm.loc[x.unique(), 'Frequency'].mean()),
        Monetary=('Customer ID', lambda x: rfm.loc[x.unique(), 'Monetary'].mean())
    )
    .reset_index()
)

segment_summary['Revenue_per_Customer'] = (
    segment_summary['Revenue'] / segment_summary['Customers']
)

segment_summary['Orders_per_Customer'] = (
    segment_summary['Orders'] / segment_summary['Customers']
)

segment_summary['Average_Order_Value'] = (
    segment_summary['Revenue'] / segment_summary['Orders']
)

segment_summary.sort_values('Revenue', ascending=False)

,Segment,Customers,Revenue,Orders,Recency,Frequency,Monetary,Revenue_per_Customer,Orders_per_Customer,Average_Order_Value
1,Champions,1297,1.185959e+07,22186,19.961449,17.105628,9143.863913,9143.863913,17.105628,534.552939
0,At Risk,1067,1.919928e+06,4461,379.991565,4.180881,1799.370106,1799.370106,4.180881,430.380610
3,Loyal Customers,701,1.856667e+06,5423,84.368046,7.736091,2648.597753,2648.597753,7.736091,342.368989
5,Regular / Mid-Value,1090,1.022468e+06,2734,75.524771,2.508257,938.043774,938.043774,2.508257,373.982339
4,Potential Customers,443,3.922670e+05,647,28.106095,1.460497,885.478600,885.478600,1.460497,606.285966
2,Inactive / Low Value,1280,3.238831e+05,1518,467.322656,1.185938,253.033680,253.033680,1.185938,213.361733